import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "~/styles/Home.module.css";
import axios from "axios";

import { useState, Dispatch, SetStateAction, useEffect } from "react";

type Todo = {
  userId: number;
  id: number;
  title: string;
  completed: boolean;
};

const inter = Inter({ subsets: ["latin"] });

type Props = {
  todosData: Todo[];
};

export default function Static({ todosData }: Props) {
  const [count, setCount] = useState(0);
  const [todos, setTodos] = useState<Todo[]>(todosData);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          <Button count={count} setCount={setCount} />
          <Button count={count} setCount={setCount} label="WOW so much" />
        </div>
        <div>
          {todos.map((todo) => (
            <div key={todo.id}>
              <p>{todo.title}</p>
              <small>from user: {todo.userId}</small>
            </div>
          ))}
        </div>
      </main>
    </>
  );
}

export const getStaticProps = async () => {
  //                                 ⬇ Setzt den typen vom Rückgabe wert
  const todosData = await axios.get<Todo[]>(
    "https://jsonplaceholder.typicode.com/todos"
  );
  return { props: { todosData: todosData.data } };
};

type ButtonProps = {
  count: number;
  setCount: Dispatch<SetStateAction<number>>;
  label?: string;
};

const Button = ({ count, setCount, label }: ButtonProps) => {
  return (
    <button onClick={() => setCount((prevCount) => prevCount + 1)}>
      {label || "Count"}: {count}
    </button>
  );
};
